// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJcgS8SXdZwmG8KxQ47gWb2oUt7JYMyoA',
    appId: '1:451791650536:web:59669d45ba52264415135d',
    messagingSenderId: '451791650536',
    projectId: 'unknown-23ada',
    authDomain: 'unknown-23ada.firebaseapp.com',
    storageBucket: 'unknown-23ada.firebasestorage.app',
    measurementId: 'G-E8Q32RS31S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk1H6NxmRuo8I92wR0dJbbl7xxo-6OdfI',
    appId: '1:451791650536:android:5def08895d398ecf15135d',
    messagingSenderId: '451791650536',
    projectId: 'unknown-23ada',
    storageBucket: 'unknown-23ada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEifFNR9qK0yfpbLl9M_P9WfttTsfkrJU',
    appId: '1:451791650536:ios:c4436ae108b8668a15135d',
    messagingSenderId: '451791650536',
    projectId: 'unknown-23ada',
    storageBucket: 'unknown-23ada.firebasestorage.app',
    iosBundleId: 'com.example.unknown',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEifFNR9qK0yfpbLl9M_P9WfttTsfkrJU',
    appId: '1:451791650536:ios:c4436ae108b8668a15135d',
    messagingSenderId: '451791650536',
    projectId: 'unknown-23ada',
    storageBucket: 'unknown-23ada.firebasestorage.app',
    iosBundleId: 'com.example.unknown',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJcgS8SXdZwmG8KxQ47gWb2oUt7JYMyoA',
    appId: '1:451791650536:web:4bcfc909073f0a4715135d',
    messagingSenderId: '451791650536',
    projectId: 'unknown-23ada',
    authDomain: 'unknown-23ada.firebaseapp.com',
    storageBucket: 'unknown-23ada.firebasestorage.app',
    measurementId: 'G-LLVJ1WD8T4',
  );
}
